### ISSUE TITLE
Printing Conserved Energy

### ISSUE THREAD

**Issue by gitmol777** [craabreu/afed#4]
@craabreu , Thank you very much for the feature to print 'Conserved Energy' . But when I try to print the value it raises 'Simulation integrator does not have a conserved energy'  error from 'output.py'. 
It looks like in the 'Integrator.py' file, the '_has_conserved_energy' flag does not fetch the correct value in my test example. How do I fix this problem ?

**Comment by craabreu** [comment]
@gitmol777 Thank you for posting this issue. Would you please provide a small example script that reproduces this error?

**Comment by gitmol777** [comment]
@craabreu, Thanks for your reply. First I got the error when I tested AFED with Alanine dipeptide with Amber96. Then just to check the error would reproducable with standard test example I tried the following code. Still I get the same error.  

**Code:**
```
import afed
from sys import stdout
from simtk import openmm, unit

model = afed.AlanineDipeptideModel()
simulation = model.createDefaultSimulation()
reporter = afed.StateDataReporter(
    stdout,
     10,
    step=True,
    collectiveVariables=True,
     driverParameters=True,
     parameterTemperatures=True,
    conservedEnergy=True
 )

simulation.reporters += [reporter]
simulation.step(100)
```

**Last part of the Error**
miniconda2/envs/py36/lib/python3.6/site-packages/afed-0+untagged.62.ga20556b-py3.6.egg/afed/output.py", line 171, in _initializeConstants
    raise Exception('Simulation integrator does not have a conserved energy')
Exception: Simulation integrator does not have a conserved energy

**Comment by craabreu** [comment]
@gitmol777 I have solved this issue. Please replace
```
simulation = model.createDefaultSimulation()
```
by
```
simulation = model.createDefaultSimulation(conservedEnergy=True)
```
